version: "3.8"

services:
  development:
    build:
      context: .
      target: development
    # ports:
    #   - "8000:8000"
    volumes:
      - ./src:/app # map local src dir to /app in docker container (bind mount)

  production:
    build:
      context: .
      target: production
    # ports:
    #   - "8000:8000"
